# Generated by Django 4.2.13 on 2024-10-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Название')),
                ('description_short', models.CharField(blank=True, max_length=250, verbose_name='Короткое описание')),
                ('description_long', models.CharField(blank=True, max_length=200, verbose_name='Длинное описание')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longtitude', models.FloatField(verbose_name='Долгота')),
            ],
        ),
    ]
