# Generated by Django 4.2.13 on 2024-10-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='title_short',
            field=models.TextField(null=True, verbose_name='Краткое название'),
        ),
    ]
