# Generated by Django 4.2.13 on 2024-10-13 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_place_title_short'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='longtitude',
            new_name='longitude',
        ),
    ]
