# Generated by Django 4.2.13 on 2024-11-10 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_alter_place_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='title_short',
        ),
    ]
